export interface Product {
  id: string;
  category: string;
  name: string;
  price: number;
  unit: string;
  description: string;
  image: string;
  price10: number;
  price100: number;
}

function calcPrice10(base: number): number {
  return Math.round(base * 0.95);
}

function calcPrice100(base: number): number {
  return Math.round(base * 0.88);
}

export const categories = [
  { id: "todos", label: "✨ Todos", emoji: "✨" },
  { id: "alfajores", label: "🍪 Alfajores", emoji: "🍪" },
  { id: "varios-dulces", label: "🍬 Dulces Varios", emoji: "🍬" },
  { id: "salados", label: "🥖 Salados", emoji: "🥖" },
  { id: "catering", label: "🎉 Catering", emoji: "🎉" },
  { id: "hojaldres", label: "🥐 Hojaldres", emoji: "🥐" },
  { id: "frolas", label: "🥧 Frolas", emoji: "🥧" },
  { id: "tartas", label: "🍰 Tartas", emoji: "🍰" },
  { id: "frutales", label: "🍓 Frutales", emoji: "🍓" },
  { id: "panaderia", label: "🍞 Panadería", emoji: "🍞" },
  { id: "picadas", label: "🧀 Picadas", emoji: "🧀" },
];

export const products: Product[] = [
  // ═══════════ ALFAJORES ═══════════
  {
    id: "alfajor-maicena-x1",
    category: "alfajores",
    name: "Alfajores Maicena por unidad",
    price: 2480,
    unit: "unidad",
    description: "Alfajor de maicena artesanal con dulce de leche, bañado en coco rallado.",
    image: "/images/IMG_5855.JPG",
    price10: calcPrice10(1736),
    price100: calcPrice100(1736),
  },
  {
    id: "alfajor-maicena-x6",
    category: "alfajores",
    name: "Alfajores Maicena por 6",
    price: 5400,
    unit: "caja x6",
    description: "Caja de 6 alfajores de maicena con dulce de leche artesanal.",
    image: "/images/image (4).jpg",
    price10: calcPrice10(3780),
    price100: calcPrice100(3780),
  },
  {
    id: "alfajor-maicena-x10-12",
    category: "alfajores",
    name: "Alfajores Maicena por 10/12",
    price: 8100,
    unit: "caja x10/12",
    description: "Caja de 10 a 12 alfajores de maicena con dulce de leche artesanal.",
    image: "/images/Alfajores Maicena por 10:12.JPG",
    price10: calcPrice10(5670),
    price100: calcPrice100(5670),
  },
  {
    id: "alfajor-crocante-x1",
    category: "alfajores",
    name: "Alfajores Crocante por unidad",
    price: 2750,
    unit: "unidad",
    description: "Alfajor crocante con dulce de leche, textura irresistible.",
    image: "/images/Alfajor Crocante unidad.JPG",
    price10: calcPrice10(1925),
    price100: calcPrice100(1925),
  },
  {
    id: "alfajor-crocante-x6",
    category: "alfajores",
    name: "Alfajores Crocante por 6",
    price: 7580,
    unit: "caja x6",
    description: "Caja de 6 alfajores crocantes con dulce de leche.",
    image: "/images/Alfajores crocantes x6.JPG",
    price10: calcPrice10(5306),
    price100: calcPrice100(5306),
  },
  {
    id: "alfajor-crocante-x10-12",
    category: "alfajores",
    name: "Alfajores Crocante por 10/12",
    price: 10420,
    unit: "caja x10/12",
    description: "Caja de 10 a 12 alfajores crocantes con dulce de leche.",
    image: "/images/Alfajores crocantes x12.JPG",
    price10: calcPrice10(7294),
    price100: calcPrice100(7294),
  },
  {
    id: "alfajor-chocolate-x1",
    category: "alfajores",
    name: "Alfajores Chocolate por unidad",
    price: 2750,
    unit: "unidad",
    description: "Alfajor bañado en chocolate con dulce de leche artesanal.",
    image: "",
    price10: calcPrice10(1925),
    price100: calcPrice100(1925),
  },
  {
    id: "alfajor-chocolate-x6",
    category: "alfajores",
    name: "Alfajores Chocolate por 6",
    price: 6920,
    unit: "caja x6",
    description: "Caja de 6 alfajores bañados en chocolate con dulce de leche.",
    image: "",
    price10: calcPrice10(4844),
    price100: calcPrice100(4844),
  },
  {
    id: "alfajor-chocolate-x10-12",
    category: "alfajores",
    name: "Alfajores Chocolate por 10/12",
    price: 10420,
    unit: "caja x10/12",
    description: "Caja de 10 a 12 alfajores bañados en chocolate con dulce de leche.",
    image: "",
    price10: calcPrice10(7294),
    price100: calcPrice100(7294),
  },
  {
    id: "alfajor-coco-x6",
    category: "alfajores",
    name: "Alfajores Coco por 6",
    price: 3600,
    unit: "caja x6",
    description: "Caja de 6 alfajores de coco con relleno suave. Ideales para el mate.",
    image: "/images/image (5).jpg",
    price10: calcPrice10(2520),
    price100: calcPrice100(2520),
  },
  {
    id: "alfajor-coco-x12",
    category: "alfajores",
    name: "Alfajores Coco por 12",
    price: 4500,
    unit: "caja x12",
    description: "Caja de 12 alfajores de coco con relleno suave.",
    image: "/images/coco x12.JPG",
    price10: calcPrice10(3150),
    price100: calcPrice100(3150),
  },
  {
    id: "alfajor-almendrado-x6",
    category: "alfajores",
    name: "Alfajores Almendrados por 6",
    price: 4350,
    unit: "caja x6",
    description: "Caja de 6 alfajores almendrados, textura premium artesanal.",
    image: "",
    price10: calcPrice10(3045),
    price100: calcPrice100(3045),
  },
  {
    id: "alfajor-almendrado-x12",
    category: "alfajores",
    name: "Alfajores Almendrados por 12",
    price: 8380,
    unit: "caja x12",
    description: "Caja de 12 alfajores almendrados, sabor gourmet artesanal.",
    image: "",
    price10: calcPrice10(5866),
    price100: calcPrice100(5866),
  },

  // ═══════════ VARIOS DULCES ═══════════
  {
    id: "pepas-membrillo",
    category: "varios-dulces",
    name: "Varios Dulces Pepas de membrillo",
    price: 3780,
    unit: "kg",
    description: "Pepas rellenas con membrillo casero. Crujientes por fuera, dulces por dentro.",
    image: "",
    price10: calcPrice10(2646),
    price100: calcPrice100(2646),
  },
  {
    id: "pepas-dulce-de-leche",
    category: "varios-dulces",
    name: "Varios Dulces Pepas de leche",
    price: 3890,
    unit: "kg",
    description: "Pepas artesanales con dulce de leche casero.",
    image: "",
    price10: calcPrice10(2723),
    price100: calcPrice100(2723),
  },
  {
    id: "masitas-varias",
    category: "varios-dulces",
    name: "Varios Dulces Masitas varias",
    price: 3460,
    unit: "kg",
    description: "Surtido de masitas artesanales variadas. Perfectas para compartir.",
    image: "/images/Varios Dulces Masitas varias.JPG",
    price10: calcPrice10(2422),
    price100: calcPrice100(2422),
  },
  {
    id: "materas",
    category: "varios-dulces",
    name: "Varios Dulces Materas",
    price: 4580,
    unit: "kg",
    description: "Galletitas materas ideales para acompañar el mate.",
    image: "/images/IMG_6184.JPG",
    price10: calcPrice10(3206),
    price100: calcPrice100(3206),
  },
  {
    id: "donitas-x12",
    category: "varios-dulces",
    name: "Donitas x12 unidades",
    price: 3200,
    unit: "caja x12",
    description: "Caja de 12 donitas esponjosas con glaseado dulce. Ideales para compartir.",
    image: "/images/BDAk7.jpg",
    price10: calcPrice10(2240),
    price100: calcPrice100(2816),
  },
  {
    id: "secas",
    category: "varios-dulces",
    name: "Masas secas",
    price: 4680,
    unit: "kg",
    description: "Masitas secas surtidas, calidad artesanal en cada unidad.",
    image: "/images/Varios Dulces Secas.JPG",
    price10: calcPrice10(3276),
    price100: calcPrice100(3276),
  },
  {
    id: "trufas",
    category: "varios-dulces",
    name: "Varios Dulces Trufas",
    price: 4580,
    unit: "kg",
    description: "Trufas de chocolate artesanales con cacao de primera calidad.",
    image: "",
    price10: calcPrice10(3206),
    price100: calcPrice100(3206),
  },
  {
    id: "copitos",
    category: "varios-dulces",
    name: "Copitos de chocolate x12",
    price: 6640,
    unit: "kg",
    description: "Copitos de merengue livianos que se deshacen en la boca.",
    image: "/images/Copitos de chocolate x12.JPG",
    price10: calcPrice10(4648),
    price100: calcPrice100(4648),
  },
  {
    id: "brownie-porcion",
    category: "varios-dulces",
    name: "Varios Dulces Brownie porción",
    price: 4370,
    unit: "porción",
    description: "Brownie húmedo y chocolatoso con nueces. Porción generosa.",
    image: "",
    price10: calcPrice10(4370),
    price100: calcPrice100(4370),
  },
  {
    id: "espejitos-membrillo-dulce-leche",
    category: "varios-dulces",
    name: "Varios Dulces Espejitos de membrillo o dulce de leche",
    price: 3870,
    unit: "kg",
    description: "Espejitos tradicionales con relleno de membrillo o dulce de leche.",
    image: "",
    price10: calcPrice10(3870),
    price100: calcPrice100(3870),
  },

  // ═══════════ SALADOS ═══════════
  {
    id: "saborizadas",
    category: "salados",
    name: "Salados Saborizadas",
    price: 2200,
    unit: "unidad",
    description: "Galletitas saborizadas con hierbas y especias seleccionadas.",
    image: "",
    price10: calcPrice10(1540),
    price100: calcPrice100(1540),
  },
  {
    id: "marineras",
    category: "salados",
    name: "Salados Marineras",
    price: 1920,
    unit: "unidad",
    description: "Galletas marineras crocantes para picadas, quesos y fiambres.",
    image: "",
    price10: calcPrice10(1344),
    price100: calcPrice100(1344),
  },
  {
    id: "pizzetas",
    category: "salados",
    name: "Salados Pizzetas",
    price: 700,
    unit: "unidad",
    description: "Mini pizzetas base artesanal, listas para preparar.",
    image: "",
    price10: calcPrice10(490),
    price100: calcPrice100(490),
  },
  {
    id: "pizzetas-listas",
    category: "salados",
    name: "Salados Pizzetas listas",
    price: 2220,
    unit: "unidad",
    description: "Pizzetas preparadas con salsa y muzzarella. Solo calentar.",
    image: "",
    price10: calcPrice10(1554),
    price100: calcPrice100(1554),
  },
  {
    id: "pizzas-listas",
    category: "salados",
    name: "Salados Pizzas listas",
    price: 8800,
    unit: "unidad",
    description: "Pizza grande lista para hornear con salsa casera y muzzarella.",
    image: "",
    price10: calcPrice10(6160),
    price100: calcPrice100(6160),
  },
  {
    id: "pre-pizzas",
    category: "salados",
    name: "Salados Pre pizzas",
    price: 2660,
    unit: "unidad",
    description: "Bases de pizza artesanales para personalizar a tu gusto.",
    image: "",
    price10: calcPrice10(1862),
    price100: calcPrice100(1862),
  },
  {
    id: "plancha-pizza-45x70",
    category: "salados",
    name: "Salados Planchas de pizzas 45x70",
    price: 28700,
    unit: "plancha",
    description: "Plancha grande de pizza (45x70cm). Ideal para eventos y locales.",
    image: "",
    price10: calcPrice10(20090),
    price100: calcPrice100(20090),
  },
  {
    id: "plancha-pizza-45x50",
    category: "salados",
    name: "Salados Planchas de pizzas 45x50",
    price: 21600,
    unit: "plancha",
    description: "Plancha de pizza (45x50cm) para reuniones familiares.",
    image: "",
    price10: calcPrice10(15120),
    price100: calcPrice100(15120),
  },
  {
    id: "torta-salada-grande",
    category: "salados",
    name: "Salados Torta salada grande",
    price: 47420,
    unit: "unidad",
    description: "Torta salada grande con relleno abundante para eventos.",
    image: "",
    price10: calcPrice10(33194),
    price100: calcPrice100(33194),
  },
  {
    id: "torta-salada-chica",
    category: "salados",
    name: "Salados Torta salada chica",
    price: 32450,
    unit: "unidad",
    description: "Torta salada chica con relleno casero y masa hojaldrada.",
    image: "",
    price10: calcPrice10(22715),
    price100: calcPrice100(22715),
  },
  {
    id: "empanadas-copetin",
    category: "salados",
    name: "Salados Empanadas copetín",
    price: 5420,
    unit: "docena",
    description: "Mini empanadas de copetín, variedad de gustos. Ideales para eventos.",
    image: "",
    price10: calcPrice10(3794),
    price100: calcPrice100(3794),
  },

  // ═══════════ CATERING ═══════════
  {
    id: "mesa-dulce-grande",
    category: "catering",
    name: "Catering Mesa dulce grande",
    price: 13180,
    unit: "por persona",
    description: "Mesa dulce completa para eventos grandes con variedad artesanal.",
    image: "",
    price10: calcPrice10(9226),
    price100: calcPrice100(9226),
  },
  {
    id: "mesa-dulce-chica",
    category: "catering",
    name: "Catering Mesa dulce chica",
    price: 10920,
    unit: "por persona",
    description: "Mesa dulce para eventos íntimos con selección artesanal.",
    image: "/images/IMG_5836.JPG",
    price10: calcPrice10(7644),
    price100: calcPrice100(7644),
  },

  // ═══════════ HOJALDRES ═══════════
  {
    id: "madrilenos-x2",
    category: "hojaldres",
    name: "Hojaldres Madrileños por 2",
    price: 3600,
    unit: "pack x2",
    description: "Par de madrileños hojaldrados con dulce de leche artesanal.",
    image: "/images/Hojaldres Madrileños por 2.JPG",
    price10: calcPrice10(2520),
    price100: calcPrice100(2520),
  },
  {
    id: "canoncitos-ddl-con-bano",
    category: "hojaldres",
    name: "Hojaldres Cañoncitos DDL c/baño",
    price: 5440,
    unit: "unidad",
    description: "Cañoncitos de hojaldre con dulce de leche y baño de chocolate.",
    image: "",
    price10: calcPrice10(3808),
    price100: calcPrice100(3808),
  },
  {
    id: "canoncitos-ddl-sin-bano",
    category: "hojaldres",
    name: "Hojaldres Cañoncitos DDL s/baño",
    price: 5320,
    unit: "unidad",
    description: "Cañoncitos de hojaldre clásicos con dulce de leche sin baño.",
    image: "",
    price10: calcPrice10(3724),
    price100: calcPrice100(3724),
  },
  {
    id: "palmeritas-200g",
    category: "hojaldres",
    name: "Hojaldres Palmeritas por 200g",
    price: 5320,
    unit: "pack 200g",
    description: "Palmeritas de hojaldre caramelizadas, pack de 200g.",
    image: "",
    price10: calcPrice10(3724),
    price100: calcPrice100(3724),
  },
  {
    id: "palmeritas-1kg",
    category: "hojaldres",
    name: "Hojaldres Palmeritas por kl",
    price: 15080,
    unit: "kg",
    description: "Palmeritas de hojaldre caramelizadas por kilo.",
    image: "",
    price10: calcPrice10(10556),
    price100: calcPrice100(10556),
  },
  {
    id: "palmeron-x1",
    category: "hojaldres",
    name: "Hojaldres Palmerón por unidad",
    price: 3280,
    unit: "unidad",
    description: "Palmerón gigante de hojaldre caramelizado.",
    image: "",
    price10: calcPrice10(2296),
    price100: calcPrice100(2296),
  },
  {
    id: "churrinches-200g",
    category: "hojaldres",
    name: "Hojaldres Churrinches por 200g",
    price: 4420,
    unit: "pack 200g",
    description: "Churrinches de hojaldre artesanal, pack de 200g.",
    image: "",
    price10: calcPrice10(3094),
    price100: calcPrice100(3094),
  },
  {
    id: "churrinches-1kg",
    category: "hojaldres",
    name: "Hojaldres Churrinches por kl",
    price: 15440,
    unit: "kg",
    description: "Churrinches de hojaldre artesanal por kilo.",
    image: "",
    price10: calcPrice10(10808),
    price100: calcPrice100(10808),
  },
  {
    id: "hojaldre-manzana-x2",
    category: "hojaldres",
    name: "Hojaldres Hojaldre con Manzana (2u)",
    price: 2100,
    unit: "pack x2",
    description: "Hojaldre relleno de manzana caramelizada con canela, 2 unidades.",
    image: "/images/image (6).jpg",
    price10: calcPrice10(1470),
    price100: calcPrice100(1470),
  },

  // ═══════════ FROLAS ═══════════
  {
    id: "frola-p15",
    category: "frolas",
    name: "Frolas P.15 membrillo/ DDL/Batata",
    price: 2540,
    unit: "unidad",
    description: "Pasta frola chica (15cm) con dulce de membrillo o batata.",
    image: "/images/Frola 15.JPG",
    price10: calcPrice10(1778),
    price100: calcPrice100(1778),
  },
  {
    id: "frola-p20",
    category: "frolas",
    name: "Frolas P.20 membrillo/ DDL/Batata",
    price: 5040,
    unit: "unidad",
    description: "Pasta frola mediana (20cm) con masa mantecosa y dulce casero.",
    image: "/images/Frola 20.JPG",
    price10: calcPrice10(3528),
    price100: calcPrice100(3528),
  },
  {
    id: "frola-p23",
    category: "frolas",
    name: "Frolas P.23 membrillo/ DDL/Batata",
    price: 5800,
    unit: "unidad",
    description: "Pasta frola grande (23cm) con generoso relleno casero.",
    image: "/images/image (10).jpg",
    price10: calcPrice10(4060),
    price100: calcPrice100(4060),
  },
  {
    id: "frola-p33",
    category: "frolas",
    name: "Frolas P.33 membrillo/ DDL/Batata",
    price: 10360,
    unit: "unidad",
    description: "Pasta frola extra grande (33cm) para eventos y celebraciones.",
    image: "/images/frola 33.JPG",
    price10: calcPrice10(7252),
    price100: calcPrice100(7252),
  },

  // ═══════════ TARTAS ═══════════
  {
    id: "tarta-p15",
    category: "tartas",
    name: "Tartas P.15",
    price: 2780,
    unit: "unidad",
    description: "Tarta artesanal chica (15cm) con relleno a elección.",
    image: "",
    price10: calcPrice10(1946),
    price100: calcPrice100(1946),
  },
  {
    id: "tarta-p20",
    category: "tartas",
    name: "Tartas P.20",
    price: 5270,
    unit: "unidad",
    description: "Tarta artesanal mediana (20cm) con relleno casero generoso.",
    image: "",
    price10: calcPrice10(3689),
    price100: calcPrice100(3689),
  },
  {
    id: "tarta-p23",
    category: "tartas",
    name: "Tartas P.23",
    price: 6070,
    unit: "unidad",
    description: "Tarta artesanal grande (23cm) con relleno abundante.",
    image: "",
    price10: calcPrice10(4249),
    price100: calcPrice100(4249),
  },
  {
    id: "tarta-p33",
    category: "tartas",
    name: "Tartas P.33",
    price: 10440,
    unit: "unidad",
    description: "Tarta artesanal extra grande (33cm) ideal para eventos.",
    image: "",
    price10: calcPrice10(7308),
    price100: calcPrice100(7308),
  },
  {
    id: "tarta-mixta",
    category: "tartas",
    name: "Tarta mixta",
    price: 6000,
    unit: "unidad",
    description: "Tarta artesanal con variedad de sabores, combinación especial.",
    image: "/images/image (7).jpg",
    price10: calcPrice10(6000),
    price100: calcPrice100(6000),
  },

  // ═══════════ FRUTALES ═══════════
  {
    id: "frutal-p20",
    category: "frutales",
    name: "Frutales P.20",
    price: 23000,
    unit: "unidad",
    description: "Torta frutal mediana (20cm) con frutas frescas y crema pastelera.",
    image: "",
    price10: calcPrice10(16100),
    price100: calcPrice100(16100),
  },
  {
    id: "frutal-p23",
    category: "frutales",
    name: "Frutales P.23",
    price: 30000,
    unit: "unidad",
    description: "Torta frutal grande (23cm) decorada con frutas frescas de estación.",
    image: "",
    price10: calcPrice10(21000),
    price100: calcPrice100(21000),
  },
  {
    id: "frutal-p33",
    category: "frutales",
    name: "Frutales P.33",
    price: 41800,
    unit: "unidad",
    description: "Torta frutal extra grande (33cm) para grandes eventos.",
    image: "",
    price10: calcPrice10(29260),
    price100: calcPrice100(29260),
  },

  // ═══════════ PANADERÍA ═══════════
  {
    id: "pan-saborizado-kg",
    category: "panaderia",
    name: "Panadería Pan saborizado por kl",
    price: 7040,
    unit: "kg",
    description: "Pan saborizado artesanal con hierbas, especias y aceite de oliva.",
    image: "",
    price10: calcPrice10(4928),
    price100: calcPrice100(4928),
  },
  {
    id: "plancha-frola-tarta-coco-toffee",
    category: "panaderia",
    name: "Panadería Plancha Frola/Tarta (Coco/Toffe)",
    price: 48510,
    unit: "plancha",
    description: "Plancha grande de frola o tarta sabor coco o toffee.",
    image: "",
    price10: calcPrice10(33957),
    price100: calcPrice100(33957),
  },
  {
    id: "plancha-banana-manzana",
    category: "panaderia",
    name: "Panadería Plancha Banana o Manzanas",
    price: 50000,
    unit: "plancha",
    description: "Plancha grande de torta de banana o manzana artesanal.",
    image: "",
    price10: calcPrice10(35000),
    price100: calcPrice100(35000),
  },
  {
    id: "budin-chico",
    category: "panaderia",
    name: "Panadería Budín chico",
    price: 5180,
    unit: "unidad",
    description: "Budín artesanal chico, húmedo y esponjoso.",
    image: "",
    price10: calcPrice10(3626),
    price100: calcPrice100(3626),
  },
  {
    id: "budin-grande",
    category: "panaderia",
    name: "Panadería Budín grande",
    price: 9490,
    unit: "unidad",
    description: "Budín artesanal grande con ingredientes premium.",
    image: "",
    price10: calcPrice10(6643),
    price100: calcPrice100(6643),
  },
  {
    id: "marineras-955-base",
    category: "panaderia",
    name: "Panadería Marineras (955 base)",
    price: 1910,
    unit: "unidad",
    description: "Galletas marineras artesanales crocantes.",
    image: "",
    price10: calcPrice10(1337),
    price100: calcPrice100(1337),
  },
  {
    id: "combinadas",
    category: "panaderia",
    name: "Panadería Combinadas",
    price: 5800,
    unit: "kg",
    description: "Surtido combinado de panificados artesanales variados.",
    image: "",
    price10: calcPrice10(4060),
    price100: calcPrice100(4060),
  },
  {
    id: "porcion-frola",
    category: "panaderia",
    name: "Panadería Porción de frola",
    price: 2400,
    unit: "porción",
    description: "Porción generosa de pasta frola artesanal.",
    image: "",
    price10: calcPrice10(1680),
    price100: calcPrice100(1680),
  },
  {
    id: "panettones",
    category: "panaderia",
    name: "Panadería Panettones",
    price: 5080,
    unit: "unidad",
    description: "Panettone artesanal con frutas y chips de chocolate.",
    image: "",
    price10: calcPrice10(3556),
    price100: calcPrice100(3556),
  },
  {
    id: "roscas",
    category: "panaderia",
    name: "Panadería Roscas",
    price: 5150,
    unit: "unidad",
    description: "Roscas artesanales esponjosas y aromáticas.",
    image: "/images/Panaderia roscas.JPG",
    price10: calcPrice10(3605),
    price100: calcPrice100(3605),
  },

  // ═══════════ PICADAS ═══════════
  {
    id: "picada-chica",
    category: "picadas",
    name: "Picadas Chica",
    price: 7000,
    unit: "unidad",
    description: "Picada chica con quesos, fiambres, aceitunas y crackers. 2-3 personas.",
    image: "",
    price10: calcPrice10(4900),
    price100: calcPrice100(4900),
  },
  {
    id: "picada-grande",
    category: "picadas",
    name: "Picadas Grande",
    price: 8400,
    unit: "unidad",
    description: "Picada grande con quesos, fiambres premium y acompañamientos. 4-6 personas.",
    image: "",
    price10: calcPrice10(5880),
    price100: calcPrice100(5880),
  },
  {
    id: "picada-completa",
    category: "picadas",
    name: "Picadas Completa",
    price: 23160,
    unit: "unidad",
    description: "Picada completa premium con todo incluido. 8+ personas.",
    image: "",
    price10: calcPrice10(16212),
    price100: calcPrice100(16212),
  },
];

export function formatPrice(price: number): string {
  return new Intl.NumberFormat("es-AR", {
    style: "currency",
    currency: "ARS",
    minimumFractionDigits: 0,
    maximumFractionDigits: 0,
  }).format(price);
}

export function getProductsByCategory(categoryId: string): Product[] {
  if (categoryId === "todos") return products;
  return products.filter((p) => p.category === categoryId);
}

export function getDiscountPercentage(quantity: number): number {
  if (quantity >= 100) return 12;
  if (quantity >= 10) return 5;
  return 0;
}

export function getPriceByQuantity(basePrice: number, quantity: number): number {
  const discount = getDiscountPercentage(quantity);
  if (discount === 12) return Math.round(basePrice * 0.88);
  if (discount === 5) return Math.round(basePrice * 0.95);
  return basePrice;
}
